# Generated by Django 4.1.3 on 2022-11-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(default='', max_length=120)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
            ],
        ),
    ]
