# Generated by Django 4.1.3 on 2022-11-30 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enzi_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientbooking',
            old_name='checkin_date',
            new_name='checkin',
        ),
        migrations.RenameField(
            model_name='clientbooking',
            old_name='checkout_date',
            new_name='checkout',
        ),
    ]
