# Generated by Django 4.1.3 on 2022-11-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enzi_app', '0002_alter_clientbooking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbooking',
            name='checkin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientbooking',
            name='checkout_date',
            field=models.DateField(),
        ),
    ]
